//TYPES RELATED TO AUTHENCTICATION
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'



//FOOD ITEMS

export const LOAD_ITEMS = 'LOAD_ITEMS'
export const CREATE_ITEM = 'CREATE_ITEM'
export const FILTER_ITEMS = 'FILTER_ITEMS'
export const NEW_ORDER = 'NEW_ORDER'
export const ORDER_PLACED = 'ORDER_PLACED'
export const SEND_ORDER_COMPLETED = 'SEND_ORDER_COMPLETED'

export const PENDING_ORDERS = ' PENDING_ORDERS'
export const RECEIEVE_NEW_ORDER = ' RECEIEVE_NEW_ORDER'
export const RECEIEVE_ORDER_COMPLETED = ' RECEIEVE_ORDER_COMPLETED'
export const RECEIEVE_NEW_ITEM = ' RECEIEVE_NEW_ITEM'



//NOTIFICAITON 
export const NOTIFY  = 'NOTIFY'